version: '3.8'

services:
  web:
    build: ./docker/php-apache
    container_name: camagru_web
    ports:
      - "8443:443"
    volumes:
      - ./docker/src:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: camagru_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: camagru
      MYSQL_USER: camagru_user
      MYSQL_PASSWORD: userpassword8080
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
