services:
  web:
    build: ./docker/php-apache
    container_name: camagru_web
    ports:
      - "${WEB_PORT}:443"
    volumes:
      - ./src:/var/www/html
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
    depends_on:
      - db
    networks:
      - DB

  adminer:
    image: adminer
    container_name: camagru_adminer
    networks:
      - DB
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT}:8080"

  db:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - DB
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/01-init.sql

volumes:
  db_data:

networks:
  DB:
    driver: bridge
